### ISSUE TITLE
dist folder not created with install script

### ISSUE THREAD

**Issue by SaraJo** [Jewelbots/www#195]
When following the instructions in the README I get an error that the favicon isn't there. On examination there is no /dist folder.

**Comment by gortok** [comment]
What command did you run?

Did you run:

sh build.sh -e dev 

And had you installed gulp and the npm install commands previous? 

Do you get any output when you run those commands? If so, what is it?

**Comment by SaraJo** [comment]
yes to both. I get:

```
[16:14:46] Using gulpfile ~/Development/Jewelbots/www/gulpfile.js
[16:14:46] Starting 'scripts'...
[16:14:46] Starting 'sass'...
[16:14:46] Starting 'move-statics'...
[16:14:46] Finished 'move-statics' after 12 ms
[16:14:46] gulp-debug: static/js/site-scripts.js
[16:14:46] gulp-debug: 1 item
[16:14:46] Finished 'scripts' after 336 ms
[16:14:46] directory ./
[16:14:46] write ./style-reset.css
[16:14:47] write ./style.css
[16:14:47] Finished 'sass' after 1.03 s
[16:14:47] Starting 'compile'...
[16:14:47] Finished 'compile' after 99 ms
[16:14:47] Starting 'build'...
[16:14:47] Finished 'build' after 122 μs

> node-express@0.0.0 start /Users/sarachipps/Development/Jewelbots/www
> node ./bin/www

fs.js:898
  return binding.stat(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, stat '/Users/sarachipps/Development/Jewelbots/www/dist/favicon.ico'
    at Object.fs.statSync (fs.js:898:18)
    at favicon (/Users/sarachipps/Development/Jewelbots/www/node_modules/serve-favicon/index.js:55:15)
    at Object.<anonymous> (/Users/sarachipps/Development/Jewelbots/www/main.js:22:9)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/7.0.0/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! node-express@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-express@0.0.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-express package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-express
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-express
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/sarachipps/Development/Jewelbots/www/npm-debug.log
```

**Comment by gortok** [comment]
The gulp build command creates that dist folder. What do you get when you type:

node -v
npm -v
gulp -v

?

**Comment by gortok** [comment]
I see you're running node 7, this site was built against node4-lts, so it's possible there's an issue there. I'm not in front of a computer ATM, but that's something to check.

**Comment by SaraJo** [comment]
I installed node 4 and no dice. 
node -v: v4.6.1
npm -v: 2.15.9
gulp -v: [15:56:48] CLI version 3.9.1
[15:56:48] Local version 3.9.1

**Comment by olore** [comment]
I have a fix for this, is it still a problem?

Basically the favicon in static/html/ not static/images/  ...

```
 gulp.task('move-statics', function () {
-  gulp.src(['static/html/robots.txt', 'static/images/favicon.*' ])
-    .pipe(gulp.dest('dist')),
-  gulp.src('static/images/favicon.*')
+  gulp.src(['static/html/robots.txt', 'static/html/favicon.*' ])
```

I can make a PR if you'd like.

**Comment by SaraJo** [comment]
@olore That would be great, I fixed it locally but not on Github.
